services:
    pugx_geo_form.geo_http_adapter:
        class: "%pugx_geo_form.geo_http_adapter_class%"
        public: false

    pugx_geo_form.geo_provider:
        class: Geocoder\Provider\GoogleMaps\GoogleMaps
        arguments: ["@pugx_geo_form.geo_http_adapter", "%kernel.default_locale%", "%pugx_geo_form.region%"]
        public: false

    pugx_geo_form.geocoder:
        class: Geocoder\ProviderAggregator
        public: false

    pugx_geo_form.geo_code_manager:
        class: PUGX\GeoFormBundle\Manager\GeoCodeManager
        arguments: ["@pugx_geo_form.geocoder"]
        public: true
        calls:
            - [registerProvider, ["@pugx_geo_form.geo_provider"]]

    pugx_geo_form.geo_data_adapter:
        class: PUGX\GeoFormBundle\Adapter\GeoDataAdapter
        public: false

    pugx_geo_form.geo_form_type_subscriber:
        class: PUGX\GeoFormBundle\EventListener\GeoTypeForm
        arguments: ["@pugx_geo_form.geo_code_manager", "@pugx_geo_form.geo_data_adapter", "%pugx_geo_form.names%"]
        public: true
        tags:
            - { name: kernel.event_subscriber }

    pugx_geo_form.geo_code_type_extension:
        class: PUGX\GeoFormBundle\Form\Extension\GeoCodeExtension
        arguments: ["@pugx_geo_form.geo_form_type_subscriber"]
        public: true
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
