language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.1
          env: SYMFONY_VERSION=3.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.2
          env: SYMFONY_VERSION=4.1.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

